### PR TITLE
fix repl completion of repl natives

### LINKED ISSUE #78: The autocompletion doesn't work with REPL natives
## Issue description

The autocompletion works well with "real Pact natives" but doesn't work with REPL only commands.
Example:

```pact
pact> (expec
```
I press TAB but nothing happens... I would expect the autocompletion to propose me `(expect  )`, `(expect-failure  )`

### PR DESCRIPTION
**Pull request by rsoeldner**
closes #78 

This PR also fixes same missing AST traversals resulting in bad position matching.

PR checklist:

* [ ] Test coverage for the proposed changes
* [ ] PR description contains example output from repl interaction or a snippet from unit test output
* [ ] Any changes that could be relevant to users [have been recorded in the changelog](https://github.com/kadena-io/pact-core/blob/master/CHANGELOG.md)

Additionally, please justify why you should or should not do the following:

* [ ] Confirm replay/back compat
* [ ] Benchmark regressions
* [ ] (For Kadena engineers) Run integration-tests against a Chainweb built with this version of Pact

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1206473309875668
  - https://app.asana.com/0/0/1206417680988244

### CODE REVIEW

File: pact/Pact/Core/Builtin.hs [hunk 1]
```diff
@@ -288,7 +288,7 @@ coreBuiltinToText = \case
   CoreDistinct -> "distinct"
   CoreFormat -> "format"
   CoreEnumerate -> "enumerate"
-  CoreEnumerateStepN -> "enumerate-step"
+  CoreEnumerateStepN -> ""
```
Comment (rsoeldner) [inline pact/Pact/Core/Builtin.hs:291]: @jmcardon I feel like going through all builtins (+ overloads) should be a separate ticket. wdyt?

Comment (jmcardon) [reply pact/Pact/Core/Builtin.hs:291]: This changes hashes! Do not do this. We need to separate this out

**Review by jmcardon — CHANGES_REQUESTED** [review]

**Review by jmcardon — APPROVED** [review]
